[test]
preload = ["./src/__tests__/setup.ts"]
coverageSkipTestFiles = true
coverageIgnoreSourcemaps = true
# https://github.com/oven-sh/bun/issues/7662
coverageThreshold = { functions = 0, lines = 0.5 }
